### ISSUE TITLE
一个凑合用的掘金小册目录插件

### ISSUE THREAD

**Issue by GreenHandLittleWhite** [GreenHandLittleWhite/blog#17]
写到中途才突然想起来，应该先搜一下有没有人已经做过了，然后发现确实有……[为掘金小册添加目录](https://juejin.cn/post/6844903874415820808)，大佬是用油猴实现的

不过既然都已经弄了，那就弄弄完吧

PS：3年了，小册还是没有目录

![image](https://user-images.githubusercontent.com/39795099/213916330-02bf0c27-e7c1-4700-a3a3-da57af6bdfed.png)

---

# 起因
鄙人愚笨，看完小册常常不能完全消化，在工作中遇到问题经常会去翻找

然后突然有一天发现，为什么`web端`的小册没有目录呢🤔️，是不是我的打开方式不对

找了一圈后发现，好像真的没有……

那要不试试自己弄一个🧐

# 实现

整体思路其实蛮简单，获取到标题后显示出来就行了，chrome相关的网上搜一下还挺多的，现学现卖

## manifest.json

首先是一个配置文件：

```json
{
  "manifest_version": 3, // 插件程序的版本号，现在得用3
  "name": "juejin-study", // 插件名称
  "version": "0.0.1", // 插件版本
  "description": "An extension for juejin, help you to study", // 插件描述
  "background": {
    "service_worker": "src/background/index.js" // 后台常驻的部分
  },
  "content_scripts": [ // 在指定页面上运行的内容脚本
    {
      "run_at": "document_idle", // 运行时机
      "matches": ["https://juejin.cn/*"], // 匹配掘金网址
      "js": ["src/content/index.js"], // 匹配到后加载的js文件
      "css": ["src/content/index.css"] // 匹配到后加载的css
    }
  ],
  "action": {
    "default_popup": "src/popup/index.html" // popup 弹框，就是点击图标后显示的弹窗内容
  },
  "icons": {
    "128": "icon.png" // 图标
  },
  "permissions": ["webRequest", "storage"], // 权限，此处用到了网络请求和存储
  "host_permissions": ["*://*.juejin.cn/*"] // 需要处理的接口，在下面的 background 中，只涉及到一个接口
}
```

## background

`background`是后台常驻的部分，通过脚本文件一直在后台运行来监控浏览器的变化

```typescript
chrome.webRequest.onCompleted.addListener(
    (details) => {
        if (details.statusCode === 200) {
            chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
                if (tabs[0].id) {
                    chrome.tabs.sendMessage(tabs[0].id, { msg: 'getBookData' });
                }
            });
        }
    },
    {
        urls: ['https://api.juejin.cn/booklet_api/v1/section/get*'],
        types: ['xmlhttprequest']
    },
    ['responseHeaders']
);

chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    if (!tab.url?.match(/^https:\/\/juejin\.cn.*/)) {
        return;
    }

    if (changeInfo.status === 'complete') {
        chrome.tabs.sendMessage(tabId, { msg: 'tabOnUpdated' });
    }
});
```

此处监听了两部分

1. 网络请求

通过查找发现小册的内容是`https://api.juejin.cn/booklet_api/v1/section/get`这个接口获取的，当请求完成后，我们给当前的tab页发送一个消息，之后在`content_scripts`中去接收

![image](https://user-images.githubusercontent.com/39795099/213916356-692af848-d473-4087-af2f-55b4334ec3e3.png)

2. tab变化

监听tab变化的原因是，当从其他地方进入小册页时需要添加目录，退出小册页时需要把目录给删了。

先判断是否是掘金的页面，然后当tab更新完成的时候发送一个消息，也是在`content_scripts`中去接收

## content

`content`是内容脚本部分，在这里进行消息的接收和对页面内容的操作

主要逻辑是这么几块：

1. 接收消息
2. 页面切换时看是否匹配到小册页，进行目录的添加或者移除
3. 获取各标题并显示目录
4. 标题高亮效果
5. 监听页面滚动，设置高亮
6. 章节切换时的loading状态

想清楚逻辑也没啥难度，就是平时原生js写的不多，边查边做

>这边有个特殊点在获取标题的地方，可能是dom更新比较慢，在使用浏览器前进后退时，获取到的不是最新的，我这边加了一个延迟来解决，暂时没想到什么好办法

代码如下：

```typescript
const baseClass = 'juejin-study';
const collapsedKey = 'juejinCollapsed';

let globalHeadings: NodeListOf<HTMLElement>;
let globalAnchors: NodeListOf<HTMLAnchorElement>;

window.addEventListener('scroll', onScroll);

function removeActiveClass() {
    document.querySelectorAll(`.${baseClass}.item`).forEach((item) => {
        item.classList.remove('active');
    });
}

function addActiveClass(anchors: NodeListOf<HTMLAnchorElement>, id?: string) {
    for (let i = 0; i < anchors.length; i++) {
        if (anchors[i].href.split('#')[1] === id) {
            if (!anchors[i]?.parentElement?.parentElement?.classList.contains('active')) {
                removeActiveClass();
                anchors[i].parentElement?.parentElement?.classList.add('active');
            }
            break;
        }
    }
}

// 设置高亮
function activeAnchor() {
    for (let i = globalHeadings.length - 1; i >= 0; i--) {
        // i === 0，初始化时没有滚动，高度不够，默认高亮第一个
        if (document.documentElement.scrollTop >= globalHeadings[i].offsetTop - 96 || i === 0) {
            addActiveClass(globalAnchors, globalHeadings[i].dataset.id);
            break;
        }
    }
}

function onScroll() {
    if (!globalHeadings || !globalAnchors) {
        return;
    }
    activeAnchor();
}

function appendSkeleton() {
    const fragment = document.createDocumentFragment();

    const skeleton = document.createElement('div');
    skeleton.className = `${baseClass} catalog-skeleton`;

    for (let i = 0; i < 4; i++) {
        const skeletonLine = document.createElement('div');
        skeletonLine.className = `${baseClass} catalog-skeleton-line`;
        skeleton.appendChild(skeletonLine);
    }
    fragment.appendChild(skeleton);

    const catalogBody = document.querySelector(`.${baseClass}.catalog-body`);
    if (catalogBody?.firstChild) {
        catalogBody.removeChild(catalogBody.firstChild);
    }
    catalogBody?.appendChild(fragment);
}

function appendCatalogList(headings: NodeListOf<HTMLElement>) {
    const fragment = document.createDocumentFragment();

    const catalogUl = document.createElement('ul');
    catalogUl.className = `${baseClass} catalog-list`;
    fragment.appendChild(catalogUl);

    const liArr: {
        level: string;
        dom: HTMLLIElement;
    }[] = [];

    headings.forEach((item, i) => {
        const itemTagLevel = item.tagName.slice(-1);
        const catalogLi = document.createElement('li');
        catalogLi.className = `${baseClass} item d${itemTagLevel}`;
        const aContainer = document.createElement('div');
        aContainer.className = 'a-container';
        const a = document.createElement('a');
        a.className = 'catalog-aTag';
        a.href = `#${item.dataset.id}`;
        a.title = item.innerText;
        a.innerText = item.innerText;
        a.onclick = function (e) {
            if (e.preventDefault) {
                e.preventDefault();
            }

            const top = item.getBoundingClientRect().top;
            document.documentElement.scrollTop = document.documentElement.scrollTop + top - 90;
        };
        aContainer.appendChild(a);
        catalogLi.appendChild(aContainer);

        liArr.push({
            level: itemTagLevel,
            dom: catalogLi
        });

        for (let j = i - 1; j >= 0; j--) {
            const prevItem = liArr[j];
            if (prevItem.level < itemTagLevel) {
                prevItem.dom.appendChild(catalogLi);
                break;
            }

            if (j === 0) {
                catalogUl.appendChild(catalogLi);
            }
        }

        if (i === 0) {
            catalogUl.appendChild(catalogLi);
        }
    });

    const catalogBody = document.querySelector(`.${baseClass}.catalog-body`);
    if (catalogBody?.firstChild) {
        catalogBody.removeChild(catalogBody.firstChild);
    }
    catalogBody?.appendChild(fragment);
}

async function appendCatalogContainer() {
    const fragment = document.createDocumentFragment();

    const catalogContainer = document.createElement('div');
    const storage = await chrome.storage.local.get(collapsedKey);
    const collapsed = storage[collapsedKey];
    catalogContainer.className = `${baseClass} article-catalog${!!collapsed ? ' collapsed' : ''}`;
    fragment.appendChild(catalogContainer);

    const toggleContainer = document.createElement('div');
    toggleContainer.className = `${baseClass} catalog-toggle-container`;
    toggleContainer.onclick = function (e) {
        if (e.target instanceof Element) {
            if (e.target.parentElement?.classList.contains('collapsed')) {
                e.target.parentElement.classList.remove('collapsed');
                chrome.storage.local.remove(collapsedKey);
            } else {
                e.target.parentElement?.classList.add('collapsed');
                chrome.storage.local.set({ [collapsedKey]: true });
            }
        }
    };
    const toggle = document.createElement('div');
    toggle.innerText = '❯';
    toggle.className = `${baseClass} catalog-toggle`;
    toggleContainer.appendChild(toggle);
    catalogContainer.appendChild(toggleContainer);

    const catalogTitle = document.createElement('div');
    catalogTitle.innerText = '目录';
    catalogTitle.className = `${baseClass} catalog-title`;
    catalogContainer.appendChild(catalogTitle);

    const catalogBody = document.createElement('div');
    catalogBody.className = `${baseClass} catalog-body`;
    catalogContainer.appendChild(catalogBody);

    document.body.appendChild(fragment);
}

// 默认有 100 延迟是因为使用浏览器前进后退时，获取到的标题不是最新的，暂时没想到好的办法
function getHeadingsWithDelay(delay = 100) {
    return new Promise<NodeListOf<HTMLElement>>((resolve) => {
        setTimeout(() => {
            const headings: NodeListOf<HTMLElement> = document.querySelectorAll(
                '.article-content .markdown-body h1, h2, h3, h4, h5'
            );
            resolve(headings);
        }, delay);
    });
}

async function getHeadings() {
    const headings = await getHeadingsWithDelay();

    if (!headings.length) {
        // 防止没拿到，再试一次
        const res = await getHeadingsWithDelay(1000);
        return res;
    }

    return headings;
}

function matchLocation() {
    const match = window.location.pathname.match(/\/(book|video)\/(\d+)\/section\/(\d+)/);
    return match;
}

async function handleGetBookData() {
    const match = matchLocation();
    if (!match) {
        return;
    }

    // 获取所有标题
    const headings = await getHeadings();
    if (!headings) {
        const catalogBody = document.querySelector(`.${baseClass}.catalog-body`);
        if (catalogBody?.firstChild) {
            catalogBody.removeChild(catalogBody.firstChild);
        }
        const emptyTip = document.createElement('div');
        emptyTip.innerText = '没有获取到';
        emptyTip.className = `${baseClass} catalog-empty`;
        catalogBody?.appendChild(emptyTip);
        return;
    }

    // 显示目录
    appendCatalogList(headings);

    globalHeadings = headings;
    globalAnchors = document.querySelectorAll(`.${baseClass}.article-catalog .catalog-aTag`);

    activeAnchor();
}

async function handleTabUpdated() {
    const match = matchLocation();
    const oldCatalogContainer = document.querySelector(`.${baseClass}.article-catalog`);
    if (!match) {
        if (oldCatalogContainer) {
            oldCatalogContainer.remove();
        }

        return;
    }

    if (!oldCatalogContainer) {
        await appendCatalogContainer();
    }

    appendSkeleton();
}

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.msg === 'tabOnUpdated') {
        handleTabUpdated();
    }
    if (request.msg === 'getBookData') {
        handleGetBookData();
    }
});
```

## 样式

样式是小问题，都是从掘金里扒的

```less
@shadow-color: rgb(0 0 0 / 15%);
@base-padding: 11px;
@padding-distance: 15px;

.juejin-study {
    &.article-catalog {
        position: fixed;
        right: 20px;
        top: 90px;
        width: 25rem;
        padding: 0;
        border-radius: 4px;
        background: #fff;
        box-shadow: 0px 0px 8px @shadow-color;
        transition: right 0.3s;

        &.collapsed {
            right: -25rem;

            .catalog-toggle {
                transform: rotate(180deg);
            }
        }
    }
    &.catalog-toggle-container {
        position: absolute;
        top: 8px;
        left: -20px;
        background: #fff;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 20px;
        height: 40px;
        border-radius: 4px 0 0 4px;
        box-shadow: -2px -2px 3px -1px @shadow-color, -2px 2px 3px -1px @shadow-color;
        cursor: pointer;

        .catalog-toggle {
            font-size: 16px;
            color: #ccc;
            transition: transform 0.3s;
            pointer-events: none;
        }
    }
    &.catalog-title {
        font-weight: 500;
        padding: 1.333rem 0;
        margin: 0 1.667rem;
        font-size: 16px;
        line-height: 2rem;
        color: #1d2129;
        border-bottom: 1px solid #e4e6eb;
    }
    &.catalog-body {
        position: relative;
        max-height: 460px;
        margin: 8px 4px 0 0;
        overflow: auto;
    }
    &.catalog-list {
        position: relative;
        line-height: 22px;
        padding: 0 0 12px;

        .item {
            margin: 0;
            padding: 0;
            font-size: 1.167rem;
            font-weight: 400;
            line-height: 22px;
            color: #333;
            list-style: none;

            .a-container {
                display: block;
                position: relative;
                padding: 0 0 0 12px;
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;

                .catalog-aTag {
                    color: inherit;
                    display: inline-block;
                    padding: 8px;
                    width: 90%;
                    white-space: nowrap;
                    overflow: hidden;
                    text-overflow: ellipsis;
                }
                &:hover .catalog-aTag {
                    background-color: #f7f8fa;
                    border-radius: 4px;
                }
            }
            &.active > .a-container {
                color: #007fff;

                &::before {
                    content: '';
                    position: absolute;
                    top: 4px;
                    left: 0;
                    margin-top: 7px;
                    width: 4px;
                    height: 16px;
                    background: #1e80ff;
                    border-radius: 0 4px 4px 0;
                }
            }
            &.d1 {
                > .a-container {
                    margin: 0;
                    padding: 0 0 0 @base-padding;
                }
            }
            &.d2 {
                > .a-container {
                    padding-left: @base-padding + @padding-distance * 1;
                }
            }
            &.d3 {
                > .a-container {
                    padding-left: @base-padding + @padding-distance * 2;
                }
            }
            &.d4 {
                > .a-container {
                    padding-left: @base-padding + @padding-distance * 3;
                }
            }
            &.d5 {
                > .a-container {
                    padding-left: @base-padding + @padding-distance * 4;
                }
            }
        }
    }
    &.catalog-empty {
        padding: 12px 16px 20px 20px;
        font-size: 1.167rem;
        color: #999;
    }
    &.catalog-skeleton {
        padding: 12px 16px 20px 20px;
        overflow: hidden;

        &-line {
            width: 100%;
            margin-bottom: 16px;
            height: 14px;
            background: linear-gradient(90deg, #e4e6eb, rgba(228, 230, 235, 0.5), #e4e6eb);
            background-size: 480px 480px;
            animation: skeleton 0.6s linear infinite;

            &:first-child {
                width: 40%;
                margin-top: 8px;
            }
            &:nth-child(3) {
                width: 80%;
            }
            &:last-child {
                width: 60%;
                margin-bottom: 0;
            }
        }
    }
}

@keyframes skeleton {
    0% {
        background-position: 0 0;
    }
    100% {
        background-position: 480px 0;
    }
}

```

至此，一个凑合用的小册目录插件就完成了

# 地址

[插件地址](https://chrome.google.com/webstore/detail/juejin-study/hpkopcfchneolmnapefkebbnddokmmae?hl=zh-CN&authuser=0)，[项目地址](https://github.com/GreenHandLittleWhite/juejin-study)，可以在[releases](https://github.com/GreenHandLittleWhite/juejin-study/releases)中下载到本地加载扩展程序

# 最后

如果有bug，请刷新页面~~并无视它，又不是不能用~~

祝 学习愉快
